# модуль содержит словарь соответствий имен клубов по kassiesa.net и api-football.com для парсинга UEFA club ranking
# {pars:apifootball}
def clubname_fix():
    ClubName = {
                'West Ham United':'West Ham',
                'Tottenham Hotspur':'Tottenham',
                'Bayern MÃ¼nchen':'Bayern Munich',
                'FC Barcelona':'Barcelona',
                'AtlÃ©tico Madrid':'Atletico Madrid',
                'Paris Saint-Germain':'Paris Saint Germain',
                'Olympique Lyon':'Lyon',
                'Stade Rennais':'Rennes',
                'Lille OSC':'Lille',
                'Internazionale':'Inter',
                'Olympique Marseille':'Marseille',
                'Sporting CP Lisbon':'Sporting CP',
                'Sporting Braga':'SC Braga',
                'Toulouse FC':'Toulouse',
                'RC Lens':'Lens',
                'Glasgow Rangers':'Rangers',
                'Club Brugge':'Club Brugge KV',
                'AA Gent':'Gent',
                'Union Saint-Gilloise':'Union St. Gilloise',
                'Viktoria Plzen':'Plzen',
                'FC Basel':'FC Basel 1893',
                'Young Boys':'BSC Young Boys',
                'Servette FC Genève':'Servette FC',
                'FC KÃ¸benhavn':'FC Copenhagen',
                'FC Salzburg':'Red Bull Salzburg',
                'LASK':'Lask Linz',
                'Red Star Belgrade':'FK Crvena Zvezda',
                'PAOK Thessaloniki':'PAOK',
                'Maccabi Tel-Aviv':'Maccabi Tel Aviv',
                'FenerbahÃ§e':'Fenerbahce',
                'Qarabag FK':'Qarabag',
                'BodÃ¸/Glimt':'Bodo/Glimt',
                'Molde FK':'Molde',
                'Ludogorets Razgrad':'Ludogorets',
                'Legia Warsaw':'Legia Warszawa',
                'FerencvÃ¡ros':'Ferencvarosi TC'
                }
    return(ClubName) 