name: init_standings

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '14 9 * * 0-6'  # каждый день в 9:14 UTC
    
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Set up Python 3.12.1  # установка версии окружения
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: "3.12.1"
      - name: repo checkout  # загрузка содержимого репозитория на вирт машину
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  
        with:
          sparse-checkout: Content_prod   # только эту папку
      - name: list current folder  # проверка загрузки
        run: ls
      - name: install Dependencies  # установка зависимостей
        run: pip install -r Content_prod/logics/requirements/req_init_standings.txt
      - name: Run script
        env:
          GH_token: ${{ secrets.FILE_UPLOAD }}
          repository: ${{ github.repository }}
          bug_mail_pass: ${{ secrets.BUG_MAIL_PASS }}
        run: python Content_prod/logics/init_standings.py
