name: standings

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '14 9 * * 0-6'  # каждый день в 9:14 UTC
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # init_standings
      - name: install init_standings Dependencies  # установка зависимостей
        run: pip install -r Content_prod/logics/requirements/req_init_standings.txt
      - name: Run script init_standings.py
        env:
          GH_token: ${{ secrets.FILE_UPLOAD }}
          repository: ${{ github.repository }}
          bug_mail_pass: ${{ secrets.BUG_MAIL_PASS }}
        run: python Content_prod/logics/init_standings.py
