name: standings_deploy

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '14 9 * * 0-6'  # каждый день в 9:14 UTC
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_token: ${{ secrets.FILE_UPLOAD }}
      repository: ${{ github.repository }}
      bug_mail_pass: ${{ secrets.BUG_MAIL_PASS }}
      apisports_key: ${{ secrets.APISPORTS_KEY }}
      UEFAcancel_date: ${{ vars.UEFA_CANCEL_DATE }}
    
    steps:
      # подготовка ОС и ПО
      - name: Set up Python 3.10  # установка версии окружения
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: "3.10"
      - name: repo checkout  # загрузка содержимого репозитория на вирт машину
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  
        with:
          sparse-checkout: |  # только необходимые папки
            Content_prod
            TL_VS_project
      - name: list current folder  # проверка загрузки
        run: ls
      
      # uefa_standings
      - name: Put current date into a variable
        run: echo "NOW=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
      - name: Run script uefa_standings.py with Dependencies only before UEFAcancel_date
        run: |
          if ${{ env.NOW < env.UEFAcancel_date }}
          then 
            pip install -r Content_prod/logics/requirements/req_uefa_standings.txt
            python Content_prod/logics/uefa_standings.py
          else
            echo "UEFA ranking influence was canceled"
          fi
      
      # TL_standings
      - name: install standings Dependencies  # установка зависимостей
        run: pip install -r Content_prod/logics/requirements/req_standings.txt
      - name: Run script standings.py
        run: python Content_prod/logics/standings.py

      # deploy
      - name: Install deploy Dependencies  # Установить зависимости
        run: pip install -r TL_VS_project/requirements_static.txt
      - name: Run script freeze    # запуск frozen-flask, создание /build
        run: python TL_VS_project/freeze.py
      - name: list build folder  # проверка адреса /build
        run: ls ./TL_VS_project/TL_flask
      - name: Deploy  # deploy происходит из внешнего репо pages из ветки gh-pages (указанной в settings), 
                      # в которую размещается папка build, созданная посредством .py на runner, запущенном из этого репо
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # When you use deploy_key, set your private key to the repository which includes this action and set your public key to your external repository.
          external_repository: Top-Liga/Top-Liga.github.io
          publish_branch: gh-pages
          publish_dir: ./TL_VS_project/TL_flask/build
