name: TEST

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_token: ${{ secrets.FILE_UPLOAD }}
      repository: ${{ github.repository }}
      bug_mail_pass: ${{ secrets.BUG_MAIL_PASS }}
      apisports_key: ${{ secrets.APISPORTS_KEY }}
    
    steps:
      # подготовка ОС и ПО
      - name: Set up Python 3.10  # установка версии окружения
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: "3.10"
      - name: repo checkout  # загрузка содержимого репозитория на вирт машину
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  
        with:
          sparse-checkout: |  # только необходимые папки
            Content_prod
            TL_VS_project
      - name: list current folder  # проверка загрузки
        run: ls

      # TEST
      - run: pip install -r Content_prod/logics/requirements/req_PyGithub.txt
      - name: Run script TEST.py
        run: python Content_prod/logics/tournaments.py
