name: TEST

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '14 9 * * 0-6'  # каждый день в 9:14 UTC
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_token: ${{ secrets.FILE_UPLOAD }}
      repository: ${{ github.repository }}
      bug_mail_pass: ${{ secrets.BUG_MAIL_PASS }}
      apisports_key: ${{ secrets.APISPORTS_KEY }}
      UEFAcancel_date: ${{ vars.UEFA_CANCEL_DATE }}
    
    steps:
      # подготовка ОС и ПО
      - name: Set up Python 3.10  # установка версии окружения
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: "3.10"
      - name: repo checkout  # загрузка содержимого репозитория на вирт машину
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  
        with:
          sparse-checkout: |  # только необходимые папки
            Content_prod
            TL_VS_project
      - name: list current folder  # проверка загрузки
        run: ls
      # common requirements
      - run: pip install -r Content_prod/logics/requirements/req_PyGithub.txt


      # uefa_standings
      - name: Put current date into a variable
        run: echo "NOW=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
      - name: Run script uefa_standings.py with Dependencies only before UEFAcancel_date
        run: |
          if ${{ env.NOW < env.UEFAcancel_date }}
          then 
            pip install -r Content_prod/logics/requirements/req_uefa_standings.txt
            python Content_prod/logics/uefa_standings.py
          else
            echo "UEFA ranking influence was canceled"
          fi
      
      # TL_standings
      - name: Run script standings.py
        run: python Content_prod/logics/standings.py

      # associations
      - name: Run script associations.py
        run: python Content_prod/logics/associations.py

      # tournaments
      - name: Run script tournaments.py
        run: python Content_prod/logics/tournaments.py

      # participants
      - name: Run script participants.py
        run: python Content_prod/logics/participants.py
