name: TEST

env:
  CRON_SCHEDULE: ${{ vars.CRON_SCHEDULE }}
  
on:
  workflow_dispatch:
  schedule:
    - cron: ${{ env.CRON_SCHEDULE }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "hello"
