name: TEST

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '14 9 * * 0-6'  # каждый день в 9:14 UTC
  
env:
  UEFAcancel_date: ${{ vars.UEFA_CANCEL_DATE }}
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "hello"
